def get_node_mappings():
    from .checkpoint_loaders import CHECKPOINT_LOADER_CLASS_MAPPINGS, CHECKPOINT_LOADER_DISPLAY_NAME_MAPPINGS
    from .lora_loaders import LORA_LOADER_CLASS_MAPPINGS, LORA_LOADER_DISPLAY_NAME_MAPPINGS
    from .controlnet_loader import CONTROLNET_LOADER_CLASS_MAPPINGS, CONTROLNET_LOADER_DISPLAY_NAME_MAPPINGS
    
    return {
        **CHECKPOINT_LOADER_CLASS_MAPPINGS,
        **LORA_LOADER_CLASS_MAPPINGS,
        **CONTROLNET_LOADER_CLASS_MAPPINGS
    }, {
        **CHECKPOINT_LOADER_DISPLAY_NAME_MAPPINGS,
        **LORA_LOADER_DISPLAY_NAME_MAPPINGS,
        **CONTROLNET_LOADER_DISPLAY_NAME_MAPPINGS
    }

